### ISSUE TITLE
[Android] In App billing showing error, if subscription is cancelled on another device

### ISSUE THREAD

**Issue by 8bhsolutions** [j3k0/cordova-plugin-purchase#1003]
### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

```
Windows 10
Cordova 9.0.1
Cordova Android 8.1.0
Device: Samsung S9+
Plugin Version: 10.0.1
Installed via: 'ionic cordova plugin add cordova-plugin-purchase'
Using my own verification server
```

### Context
My app has Monthly and Yearly subscription. Currently using test account. 

If the subscription is cancelled when the app is not open (for example cancelling on another device). Then when the cancelled subscription expires, the user is tries to buy the subscription again, it will result in error.

The error is shown in the In-App billing pop-up:

```
We are unable to change your subscription plan. Manage Subscriptions
```

Logcat  error output

```
03-10 18:09:43.724: E/Parcel(4856): Class not found when unmarshalling: com.android.billingclient.api.BillingClientImpl$1
03-10 18:09:43.724: E/Parcel(4856): java.lang.ClassNotFoundException: com.android.billingclient.api.BillingClientImpl$1
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.Class.classForName(Native Method)
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.Class.forName(Class.java:453)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.Parcel.readParcelable(Parcel.java:2781)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.Parcel.readValue(Parcel.java:2684)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.BaseBundle.getString(BaseBundle.java:1155)
03-10 18:09:43.724: E/Parcel(4856): 	at android.content.Intent.getStringExtra(Intent.java:8111)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:724)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1511)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:603)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6599)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6473)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6464)
03-10 18:09:43.724: E/Parcel(4856): 	at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10814)
03-10 18:09:43.724: E/Parcel(4856): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
03-10 18:09:43.724: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4127)
03-10 18:09:43.724: E/Parcel(4856): 	at android.os.Binder.execTransact(Binder.java:739)
03-10 18:09:43.724: E/Parcel(4856): Caused by: java.lang.ClassNotFoundException: com.android.billingclient.api.BillingClientImpl$1
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.Class.classForName(Native Method)
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
03-10 18:09:43.724: E/Parcel(4856): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-10 18:09:43.724: E/Parcel(4856): 	... 21 more
03-10 18:09:43.724: E/Parcel(4856): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-10 18:09:43.800: E/Parcel(4856): Class not found when unmarshalling: fvp
03-10 18:09:43.800: E/Parcel(4856): java.lang.ClassNotFoundException: fvp
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.Class.classForName(Native Method)
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.Class.forName(Class.java:453)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.Parcel.readParcelable(Parcel.java:2781)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.Parcel.readValue(Parcel.java:2684)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.BaseBundle.getString(BaseBundle.java:1155)
03-10 18:09:43.800: E/Parcel(4856): 	at android.content.Intent.getStringExtra(Intent.java:8111)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:724)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1511)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:603)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityStartController.startActivityInPackage(ActivityStartController.java:305)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:419)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6846)
03-10 18:09:43.800: E/Parcel(4856): 	at android.app.IActivityManager$Stub.onTransact$startActivityIntentSender$(IActivityManager.java:11496)
03-10 18:09:43.800: E/Parcel(4856): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1075)
03-10 18:09:43.800: E/Parcel(4856): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4127)
03-10 18:09:43.800: E/Parcel(4856): 	at android.os.Binder.execTransact(Binder.java:739)
03-10 18:09:43.800: E/Parcel(4856): Caused by: java.lang.ClassNotFoundException: fvp
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.Class.classForName(Native Method)
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
03-10 18:09:43.800: E/Parcel(4856): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-10 18:09:43.800: E/Parcel(4856): 	... 21 more
03-10 18:09:43.800: E/Parcel(4856): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Expected behavior
When the user opens the app to purchase the subscription, the In App billing pop up should work

### Observed behavior
When the user opens the app to purchase the same subscription, the In-app pop up shows an error

### Steps to reproduce
1. User open app on Android device, and complete purchase of Monthly subscription
2. User closes app on Android device
3. User opens Google Play Store website on PC
4. User cancels the subscription on PC
5. Wait for the Monthly subscription to expire (5 minutes when using a test account)
6. User opens app on Android device. 

- Note that the iap2 product is in Approved state.
- My verification server returned error, with reason, token expired

7. User goes to purchase Monthly subscription again.
8. The In-App billing pop up shows an error

**Comment by 8bhsolutions** [comment]
The issue is caused by setting the oldSku, even though the transaction has expired.

I have implemented a workaround in my app's javascript code to prevent sending oldSku if transaction is expired.

The core issues remains in the framework, due to timing issue between store.verify and user executing buy. The root cause is as follow:

1. When entering my subscription page, it calls store.refresh().
2. Store.refresh() gets product/transaction from billing library.
3. Product is put into Approved state
4. My store setup, calls store.verify() on product.Approved state
5. While the code is waiting for verify to return from server
6. User clicks buy subscription.
7. When user clicks buy subscription, the oldSku property is populated and sent to java code.

@j3k0 

- Is there a way to wait until refresh completes before executing order?
- Why does the product state goes back to Approved on store.refresh(), even though the state was set to VALID, because during app init the token was set as expired?

Side note:
- The logcat error ``Class not found when unmarshalling: com.android.billingclient.api.BillingClientImpl$1`` exists even if in-app pop is successful. So it must be unrelated issue.
