### ISSUE TITLE
[ANDROID] High battery usage due to continuous stream of CancellationException when user cancels subscription.

### ISSUE THREAD

**Issue by 8bhsolutions** [j3k0/cordova-plugin-purchase#1006]
### system info

```
Windows 10
Cordova 9.0.1
Cordova Android 8.1.0
Android SDK Tools : 26.1.1
Device: Samsung S9+
Plugin Version: 10.0.1
Installed via: 'ionic cordova plugin add cordova-plugin-purchase'
```

### Context
When a user cancel their Subscription. When it expires, the device will continue to throw CancellationException exception.

The impact of these exceptions is continued engagement of the CPU, resulting in high battery usage.

After closing the app, the exceptions will still continue to flood for a while. The length of time the exceptions continue to be thrown after the app is closed is dependent on how long the app is left running after the Subscription Cancellation event.

My guess is that the app queues commands to the Finsky process, so the Finsky will continue to process the command until it completes the queue.

Force Stop ``Google Play Store`` app will also stop the error.

Below is a snippet of the continuous stream of exceptions.

```
2020-03-13 11:46:20.982 16761-18144/? E/Finsky: [3509] pcm.a(3): Replication failed, request pending true
    java.util.concurrent.CancellationException: Task was cancelled.
        at aoag.a(PG:2)
        at aoag.get(PG:11)
        at aocz.a(PG:1)
        at aobv.a(PG:20)
        at aobr.run(PG:3)
        at jyh.execute(PG:1)
        at aoag.b(PG:20)
        at aoag.a(PG:16)
        at aoag.a(PG:36)
        at aoak.run(PG:3)
        at aocg.run(Unknown Source:7)
        at jyh.execute(PG:1)
        at aoch.execute(PG:1)
        at aobd.b(PG:1)
        at aobd.a(PG:3)
        at aocc.done(Unknown Source:2)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.cancel(FutureTask.java:181)
        at aobn.cancel(Unknown Source:4)
        at jyz.cancel(Unknown Source:2)
        at pdd.a(PG:19)
        at pdd.a(PG:24)
        at pcr.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at jye.run(Unknown Source:14)
        at java.lang.Thread.run(Thread.java:764)
2020-03-13 11:46:21.183 16761-18144/? E/Finsky: [3509] pcm.a(3): Replication failed, request pending true
    java.util.concurrent.CancellationException: Task was cancelled.
        at aoag.a(PG:2)
        at aoag.get(PG:11)
        at aocz.a(PG:1)
        at aobv.a(PG:20)
        at aobr.run(PG:3)
        at jyh.execute(PG:1)
        at aoag.b(PG:20)
        at aoag.a(PG:16)
        at aoag.a(PG:36)
        at aoak.run(PG:3)
        at aocg.run(Unknown Source:7)
        at jyh.execute(PG:1)
        at aoch.execute(PG:1)
        at aobd.b(PG:1)
        at aobd.a(PG:3)
        at aocc.done(Unknown Source:2)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.cancel(FutureTask.java:181)
        at aobn.cancel(Unknown Source:4)
        at jyz.cancel(Unknown Source:2)
        at pdd.a(PG:19)
        at pdd.a(PG:24)
        at pcr.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at jye.run(Unknown Source:14)
        at java.lang.Thread.run(Thread.java:764)
2020-03-13 11:46:21.183 16761-18144/? E/Finsky: [3509] pcm.a(3): Replication failed, request pending true
    java.util.concurrent.CancellationException: Task was cancelled.
        at aoag.a(PG:2)
        at aoag.get(PG:11)
        at aocz.a(PG:1)
        at aobv.a(PG:20)
        at aobr.run(PG:3)
        at jyh.execute(PG:1)
        at aoag.b(PG:20)
        at aoag.a(PG:16)
        at aoag.a(PG:36)
        at aoak.run(PG:3)
        at aocg.run(Unknown Source:7)
        at jyh.execute(PG:1)
        at aoch.execute(PG:1)
        at aobd.b(PG:1)
        at aobd.a(PG:3)
        at aocc.done(Unknown Source:2)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.cancel(FutureTask.java:181)
        at aobn.cancel(Unknown Source:4)
        at jyz.cancel(Unknown Source:2)
        at pdd.a(PG:19)
        at pdd.a(PG:24)
        at pcr.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at jye.run(Unknown Source:14)
        at java.lang.Thread.run(Thread.java:764)
```

### Expected behavior
No exceptions are thrown

### Observed behavior
CancellationException 

### Steps to reproduce

1. Buy Test subscription - Using monthly subscription, it auto renewed every 5 mins, and google play automatically cancels it in 30 mins
2. Wait for Google play to cancel the subscription
3. Observer error

**Comment by j3k0** [comment]
I never experienced that on my devices. Also the back-trace doesn't mention the plugin itself, could it be a problem in another library that monitors your subscriptions? Did you reproduce on different devices?

**Comment by 8bhsolutions** [comment]
Yes, I have reproduced in multiple Samsung S9+ devices, and also different Android emulators.
No exactly sure where the invocation comes from. But the only service in my app that interacts with subscription is through this library.

What I have also discovered (in emulator devices), using older version of Play Store + Play Service does not cause this issue

Version with issue
Play Store Version: 19.1.27-all [0] [PR] 298856675
Play Service Version: 20.06.16 (100700-296104215)

Version without issue:
Play Store: 10.1.41-all [0] [PR] 197615634
Play Service: 040700-2399467275

I have also raised a bug with Google. No response from them yet.

My guess is either there is a bug introduced in newer version of Google, or Google changed the internal working of Play Store/Service, and now there is incompatibility with how this plugin works.

**Comment by j3k0** [comment]
I'll try to check this out. If you can reproduce with a build that has debugging symbols, this could pinpoint the exact issue more precisely.

**Comment by 8bhsolutions** [comment]
Unfortunately I don't have a test app to share.

**Comment by 8bhsolutions** [comment]
Google support has replicated the bug. No indication on when they will provide a fix.
So, it seems like it is most likely an issue with Google Play Store/Service, rather than this plugin

**Comment by j3k0** [comment]
OK, thanks for the follow up.
