### ISSUE TITLE
[ANDROID] Initial load of plugin fails

### ISSUE THREAD

**Issue by p4u1d34n** [j3k0/cordova-plugin-purchase#1060]
plugin version="10.1.1"

Ionic:

Ionic CLI : 6.9.3 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 5.1.1
@angular-devkit/build-angular : 0.803.24
@angular-devkit/schematics : 8.3.26
@angular/cli : 8.3.26
@ionic/angular-toolkit : 2.2.0

Capacitor:

Capacitor CLI : 1.5.2
@capacitor/core : 1.5.2

Cordova:

Cordova CLI : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms : none
Cordova Plugins : no whitelisted plugins (2 plugins total)

Utility:

cordova-res (update available: 0.15.1) : 0.14.0
native-run (update available: 1.0.0) : 0.2.9

System:

Android SDK Tools : 26.1.1 (/Users/deano/Library/Android/sdk/)
ios-deploy : 1.9.2
NodeJS : v13.11.0 (/usr/local/bin/node)
npm : 6.13.4
OS : macOS Catalina
Xcode : Xcode 11.3.1 Build version 11C504

### Expected behavior
1593747014.129 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: state: com.thechairmansbao.tcb2.annual -> valid
1593747014.130 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: state: com.thechairmansbao.tcb2.biannual -> valid
1593747014.130 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: state: com.thechairmansbao.tcb2.monthly -> valid
1593747014.130 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: state: com.thechairmansbao.tcb2.quarterly -> valid
1593747014.131 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: iabGetPurchases()
1593747014.206 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: iabSetPurchases: []
1593747014.206 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: inappbilling.getPurchases() -> Success
1593747014.207 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG:                             -> object
1593747014.208 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG:                             -> []
1593747014.209 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: iabUpdatePurchases: []
1593747014.210 29267-29267/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] DEBUG: store.trigger -> triggering action refresh-completed

### Observed behavior
1593746390.173 22958-22958/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] WARNING: A callback in 'ready.callback' failed with an exception.
1593746390.175 22958-22958/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] WARNING:            Cannot read property 'data' of null
1593746390.176 22958-22958/the.app.i.have I/Capacitor/Console: File: capacitor-runtime.js - Line 4961 - Msg: [store.js] WARNING:            TypeError: Cannot read property 'data' of null
        at Object.<anonymous> (http://localhost/main-es2015.js:6672:79)
        at Object.callExternal (capacitor-runtime.js:5568:36)
        at Object.store.ready (capacitor-runtime.js:4367:25)
        at capacitor-runtime.js:6518:23
        at Object.callbackFromNative (capacitor-runtime.js:1265:66)
        at <anonymous>:1:142

### Steps to reproduce
from a new install, init the plugin and register products
the error shows in verbose debug

**Comment by p4u1d34n** [comment]
ignore me... i was a fool ... moving on ... nothing to see here ... 

i was trying to set : store.applicationUsername 
with a var that was not instantiated
