### ISSUE TITLE
[ANDROID] Native error when store.update() called with no store.refresh()

### ISSUE THREAD

**Issue by canadaka** [j3k0/cordova-plugin-purchase#1088]
### system info
```
Windows 10
Cordova 9.0.0
Device: Android 9
Plugin Version: 10.1.2
```

If I call store.update() on Android after registering products none of my events like `updated` fire and there is a native Java error.

```
2020-08-13 21:39:47.906 22680-22948/com.appname E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.billingclient.api.BillingClient.startConnection(com.android.billingclient.api.BillingClientStateListener)' on a null object reference
        at cc.fovea.PurchasePlugin.startServiceConnection(PurchasePlugin.java:841)
        at cc.fovea.PurchasePlugin.executeServiceRequest(PurchasePlugin.java:875)
        at cc.fovea.PurchasePlugin.queryPurchases(PurchasePlugin.java:286)
        at cc.fovea.PurchasePlugin.getPurchases(PurchasePlugin.java:236)
        at cc.fovea.PurchasePlugin.execute(PurchasePlugin.java:150)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

The same code works fine on iOS, the store.update() has no error in xcode and my `updated` event fires.

On Android if I FIRST call a store.refresh(); BEFORE calling store.update() then the above error doesn't happen.

**Comment by jedilor** [comment]
Same problem for me
