### ISSUE TITLE
Application crash after purchase

### ISSUE THREAD

**Issue by Bridgeprg** [j3k0/cordova-plugin-purchase#163]
Hi,

I use Jk30 code for Google in app payment which it work fine until you press subscribe button and go throw with purchase. After that app does not open and crash immediately as soon as you try to open it.

Below is crash log 
java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)
at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:864)
at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:576)
at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
at java.lang.Thread.run(Thread.java:841)
Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)
at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)
... 6 more

thank you

**Comment by OJcode14** [comment]
check in #145 and #103
