### ISSUE TITLE
Crash after item bought

### ISSUE THREAD

**Issue by mparpaillon** [j3k0/cordova-plugin-purchase#176]
Hi,

Thanks for the plugin it's great.
I have an issue in production with Android though.

Here is the crash report 

```
java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)
at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:864)
at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:562)
at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)
at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)
at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)
... 6 more
```

Maybe this will ring a bell... for me it's chinese

Btw, I was buying an item in test mode. I don't know if that changes anything.

Hope you can figure this out soon since the app is published and I can't run it again without a crash now...

**Comment by mparpaillon** [comment]
Duh duplicate... sorry #123
