### ISSUE TITLE
Can't start async operation (refresh inventory) because another async operation(refresh inventory) is in progress.

### ISSUE THREAD

**Issue by qwemaze** [j3k0/cordova-plugin-purchase#249]
My app crashes almost every time afer I open Play Market, close it and go back to app. 
As you can see in adb logcat it comes from InAppBillingPlugin.
Code:
```javascript
(function(){
	var platform = window.device.platform;
	var marketLink =
		platform == 'Android' ?
			'market://details?id=me.yakovalperin.nistagmus':
		platform == 'IOS' ?
			'' : null;
	var mail = "mailto:qwelias@gmail.com?subject=Reflow Feedback&body=Device info:"+JSON.stringify(window.device)+"%0A%0AMessage:%0A";
	window.feedback = function(){
		if(platform != 'Android');
		confirm(
		    'It will help us to promote the app!',
		    function(button){
		        if(button == '2'){
		            window.open(marketLink, "_system");
		        }else if(button == '3'){
		            window.open(mail);
		        }
		    }, "Want to rate us 5 stars?", ['No', 'YES!', 'Give feedback']
		);
	}
})()
```

ADB log:
```
D/AndroidRuntime(23493): Shutting down VM

E/AndroidRuntime(23493): FATAL EXCEPTION: main

E/AndroidRuntime(23493): Process: me.yakovalperin.nistagmus, PID: 23493

E/AndroidRuntime(23493): java.lang.IllegalStateException: Can't start async operation (refresh inventory) because another async operation(refresh inventory) is in progress.

E/AndroidRuntime(23493): 	at com.smartmobilesoftware.util.IabHelper.flagStartAsync(IabHelper.java:814)

E/AndroidRuntime(23493): 	at com.smartmobilesoftware.util.IabHelper.queryInventoryAsync(IabHelper.java:629)

E/AndroidRuntime(23493): 	at com.smartmobilesoftware.inappbilling.InAppBillingPlugin$1.onIabSetupFinished(InAppBillingPlugin.java:173)

E/AndroidRuntime(23493): 	at com.smartmobilesoftware.util.IabHelper$1.onServiceConnected(IabHelper.java:267)

E/AndroidRuntime(23493): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)

E/AndroidRuntime(23493): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)

E/AndroidRuntime(23493): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(23493): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(23493): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(23493): 	at android.app.ActivityThread.main(ActivityThread.java:5254)

E/AndroidRuntime(23493): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(23493): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(23493): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

E/AndroidRuntime(23493): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

W/ActivityManager(  535):   Force finishing activity 1 me.yakovalperin.nistagmus/.MainActivity
```

**Comment by qwemaze** [comment]
I've found possible solution, hope it could help you fix it.
```java
if (!mHelper.isAsyncInProgress()) {
    mHelper.launchPurchaseFlow(...);
}
```
