### ISSUE TITLE
Crash when closing app

### ISSUE THREAD

**Issue by abejfehr** [j3k0/cordova-plugin-purchase#277]
I receive a message saying "Unfortunately, [appname] has stopped" when using `navigator.app.exitApp();` to exit from an app that uses Cordova with the cordova-plugin-purchase plugin.

My logcat looks like this:

```
D/AndroidRuntime(29922): Shutting down VM
E/AndroidRuntime(29922): FATAL EXCEPTION: main
E/AndroidRuntime(29922): Process: com.abefehr.game, PID: 29922
E/AndroidRuntime(29922): java.lang.RuntimeException: Unable to destroy activity {com.abefehr.game/com.abefehr.game.MainActivity}: java.lang.IllegalArgumentException: Service not registered: com.smartmobilesoftware.util.IabHelper$1@21a73fd4
E/AndroidRuntime(29922):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
E/AndroidRuntime(29922):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
E/AndroidRuntime(29922):    at android.app.ActivityThread.access$1400(ActivityThread.java:151)
E/AndroidRuntime(29922):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
E/AndroidRuntime(29922):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(29922):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(29922):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(29922):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29922):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(29922):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(29922):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(29922): Caused by: java.lang.IllegalArgumentException: Service not registered: com.smartmobilesoftware.util.IabHelper$1@21a73fd4
E/AndroidRuntime(29922):    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1029)
E/AndroidRuntime(29922):    at android.app.ContextImpl.unbindService(ContextImpl.java:1816)
E/AndroidRuntime(29922):    at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
E/AndroidRuntime(29922):    at com.smartmobilesoftware.util.IabHelper.dispose(IabHelper.java:310)
E/AndroidRuntime(29922):    at com.smartmobilesoftware.inappbilling.InAppBillingPlugin.onDestroy(InAppBillingPlugin.java:471)
E/AndroidRuntime(29922):    at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:295)
E/AndroidRuntime(29922):    at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:476)
E/AndroidRuntime(29922):    at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:296)
E/AndroidRuntime(29922):    at android.app.Activity.performDestroy(Activity.java:6169)
E/AndroidRuntime(29922):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
E/AndroidRuntime(29922):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
E/AndroidRuntime(29922):    ... 10 more
I/OpenGLRenderer(  716): Initialized EGL, version 1.4
W/EGL_emulation(  716): eglSurfaceAttrib not implemented
W/OpenGLRenderer(  716): Failed to set EGL_SWAP_BEHAVIOR on surface 0x9d9eb4a0, error=EGL_SUCCESS
W/ResourceType(  928): No package identifier when getting value for resource number 0x00000000
W/PackageManager(  928): Failure retrieving resources for com.abefehr.game: Resource ID #0x0
W/ActivityManager(  716): Activity destroy timeout for ActivityRecord{1f35d8ed u0 com.abefehr.game/.MainActivity t46 f}
```

**Comment by tehmaestro** [comment]
I got this too. Did you manage to find a solution?

**Comment by abejfehr** [comment]
I don't have a solution yet unfortunately

**Comment by kvanniarajan** [comment]
Fix suggested on http://stackoverflow.com/a/16495756 works for me.

I had to change line 130 in plugins/cc.fovea.cordova.purchase/src/android/com/smartmobilesoftware/util/labHelper.java and platforms/android/src/com/smartmobilesoftware/util/LabHelper.java

`if (mContext != null) mContext.unbindService(mServiceConn);`
has to be changed into
`if (mContext != null && mService != null) mContext.unbindService(mServiceConn);`

**Comment by rafaellop** [comment]
I can confirm that the issue is still present in 6.0.0 on Android. I've suffered this on Nexus 7 with Android 5.0 in Google Play Firebase test lab. I've got logcat if needed. The above fix from @kvanniarajan helped. Here's the fragment of the logcat with the error:

```
FATAL EXCEPTION: main
 Process: com.creamsoft.whereismymoney, PID: 26756
 java.lang.RuntimeException: Unable to destroy activity {com.creamsoft.whereismymoney/com.creamsoft.whereismymoney.MainActivity}: java.lang.IllegalArgumentException: Service not registered: com.smartmobilesoftware.util.IabHelper$1@22cf6a9f
 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3671)
 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3689)
 	at android.app.ActivityThread.access$1400(ActivityThread.java:144)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:135)
 	at android.app.ActivityThread.main(ActivityThread.java:5221)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
 Caused by: java.lang.IllegalArgumentException: Service not registered: com.smartmobilesoftware.util.IabHelper$1@22cf6a9f
 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1024)
 	at android.app.ContextImpl.unbindService(ContextImpl.java:1802)
 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:550)
 	at com.smartmobilesoftware.util.IabHelper.dispose(IabHelper.java:334)
 	at com.smartmobilesoftware.inappbilling.InAppBillingPlugin.onDestroy(InAppBillingPlugin.java:503)
 	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:297)
 	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:480)
 	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:315)
 	at android.app.Activity.performDestroy(Activity.java:6112)
 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1140)
 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3658)
 	... 10 more
```

**Comment by hypery2k** [comment]
@j3k0 Do you plan a new release?

**Comment by j3k0** [comment]
Done.

**Comment by hypery2k** [comment]
thanks
