### ISSUE TITLE
[PGB] Android crash after successful purchase

### ISSUE THREAD

**Issue by danielefenix** [j3k0/cordova-plugin-purchase#299]
Hi everyone,

I successfully installed and made the plugin work for iOS but I can not make it work with Android.

I can successfully purchase an item but when Google says that the purchase is OK the app crashes and closes. If i try to open it again and call the store.refresh() method the app crashes again.

Additional information:
- the app is compiled with PhoneGap Build
- the cli-5.2.0  is used PhoneGap (iOS: 3.9.1  / Android: 4.1.1)
- plugin version: name="cc.fovea.cordova.purchase" source="npm" version="3.11.1"
- the billing key is set as <param name="BILLING_KEY" value="MIIBIj..."/>
- the product is well configured because I can successfully retrieve its price, title, ecc.
- the issue has been experienced on several devices
- #123 and #131 reference a similar problem, but given that they use a different compiling mechanism the solution can not be applied in my case (using PhoneGap Build)

logs:
```
E/IABUtil/Security(24158): Base64 decoding failed.

D/AndroidRuntime(24158): Shutting down VM

W/dalvikvm(24158): threadid=1: thread exiting with uncaught exception (group=0x416f1d40)

E/AndroidRuntime(24158): FATAL EXCEPTION: main

E/AndroidRuntime(24158): Process: com.xxx.xxx, PID: 24158

E/AndroidRuntime(24158): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10001, result=-1, data=Intent { (has extras) }} to activity {com.xxx.xxx/com.xxx.xxx.xxx}: java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 4: 46(decimal)

E/AndroidRuntime(24158): at android.app.ActivityThread.deliverResults(ActivityThread.java:3432)

E/AndroidRuntime(24158): at android.app.ActivityThread.handleSendResult(ActivityThread.java:3475)

E/AndroidRuntime(24158): at android.app.ActivityThread.access$1300(ActivityThread.java:139)

E/AndroidRuntime(24158): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)

E/AndroidRuntime(24158): at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(24158): at android.os.Looper.loop(Looper.java:136)

E/AndroidRuntime(24158): at android.app.ActivityThread.main(ActivityThread.java:5086)

E/AndroidRuntime(24158): at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime(24158): at java.lang.reflect.Method.invoke(Method.java:515)

E/AndroidRuntime(24158): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)

E/AndroidRuntime(24158): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

E/AndroidRuntime(24158): at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime(24158): Caused by: java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 4: 46(decimal)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.IabHelper.handleActivityResult(IabHelper.java:497)

E/AndroidRuntime(24158): at com.smartmobilesoftware.inappbilling.InAppBillingPlugin.onActivityResult(InAppBillingPlugin.java:421)

E/AndroidRuntime(24158): at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)

E/AndroidRuntime(24158): at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)

E/AndroidRuntime(24158): at android.app.Activity.dispatchActivityResult(Activity.java:5446)

E/AndroidRuntime(24158): at android.app.ActivityThread.deliverResults(ActivityThread.java:3428)

E/AndroidRuntime(24158): ... 11 more

E/AndroidRuntime(24158): Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 4: 46(decimal)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)

E/AndroidRuntime(24158): at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)

E/AndroidRuntime(24158): ... 18 more

I/SFPerfTracer(  236):      triggers: (rate: 100:2571) (compose: 0:44) (post: 0:187) (render: 0:187) (149:38557 frames) (150:114101)

D/SFPerfTracer(  236):        layers: (6:11) (DimLayer: 0:61)* (DimLayer: 0:23)* (FocusedStackFrame: 0:1487)* (StatusBar: 0:18582) (NavigationBar: 0:8159) (com.android.systemui.ImageWallpaper: 0:1254)* (DimLayer: 0:120) (DimLayer: 0:58)* (com.xxx.xxx/com.xxx.xxx.xxx: 0:66) (com.xxx.xxx/com.xxx.xxx.xxx: 150:2278) (com.android.vending/com.google.android.finsky.billing.lightpurchase.IabV3Activity: 24:550) 

W/ActivityManager(  861):   Force finishing activity com.xxx.xxx/.xxx

W/ContextImpl( 1349): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 

I/SFPerfTracer(  236):      triggers: (rate: 0:0) (36617 sw vsyncs) (0 skipped) (401:130839 vsyncs) (403:198875)

D/Checkin (15389): publish the event [tag = MOT_MEDIA_STATS_L3 event name = FILE_DOWNLOAD]

V/NQFileLogger(25272): [2377] e.a: about to write to file

V/ProcessReports(25272): [2377] ProcessReportsService.a: If not already scheduled, schedule for 3600 to 14400 seconds from now (but might be processed inline after 900 seconds instead)

I/DownloadManager(15389): Download 114 finished with status SUCCESS

I/openssl (15389): Crypto mode not selected, openssl will run on its regular mode.

I/openssl (15389): Crypto mode 0 already enabled

D/dalvikvm(24600): GC_EXPLICIT freed 607K, 41% free 10305K/17216K, paused 1ms+3ms, total 42ms

I/Gmail   (24600): MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 17983, normalSync: true

I/Gmail   (24600): lowestBackward conversation id 0

D/WifiStateMachine(  861): handleMessage: E msg.what=151572

D/WifiStateMachine(  861): processMsg: ConnectedState

D/WifiStateMachine(  861): processMsg: L2ConnectedState

D/WifiStateMachine(  861): handleMessage: X

I/Gmail   (24600): notifyAccountChanged

I/Gmail   (24600): getAccountsCursor

W/ActivityManager(  861): Activity pause timeout for ActivityRecord{42146178 u0 com.xx.xxx/.xxx t122 f}

W/ContextImpl( 1349): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 

I/openssl (15389): Crypto mode not selected, openssl will run on its regular mode.

I/openssl (15389): Crypto mode 0 already enabled

W/Settings(24328): Setting bugreport_in_power_menu has moved from android.provider.Settings.Secure to android.provider.Settings.Global.

E/Cryptfs (  223): not running with encryption, aborting
```

**Comment by Alveoli** [comment]
Hi, I have exactly the same problem - crash after successful purchase, and now crashes every time on opening the app.  cc.fovea.cordova.purchase@4.0.0  Incidentally I am using Meteor.

Error message is: `E/AndroidRuntime(12713): java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)`

Have you found any solutions?

**Comment by NGumby** [comment]
I also have the same issue as @Alveoli.  This is the crash report after the purchase : 
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10001, result=-1, data=Intent { (has extras) }} to activity {ca.compusport.compusport/ca.compusport.compusport.MainActivity}: java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3581)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3624)
	at android.app.ActivityThread.access$1300(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1333)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)
	at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
	at com.smartmobilesoftware.util.IabHelper.handleActivityResult(IabHelper.java:497)
	at com.smartmobilesoftware.inappbilling.InAppBillingPlugin.onActivityResult(InAppBillingPlugin.java:425)
	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
	at android.app.Activity.dispatchActivityResult(Activity.java:6222)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3577)
	... 10 more
Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)
	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)
```

And this is on startup every time after the initial crash :

```
java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)
	at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
	at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:864)
	at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:562)
	at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
	at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)
	at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)
	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)
	... 6 more
```

**Comment by grigio** [comment]
Is this still an issue? Are there workarounds? Which android sdk do you raccomend?
Thanks

**Comment by c-h-** [comment]
@grigio Installing from GitHub rather than NPM is what fixed it for my users (no idea why):

```bash
cordova plugin add https://github.com/j3k0/cordova-plugin-purchase --variable BILLING_KEY="<Billing key>"
```

**Comment by j3k0** [comment]
The issues described here seems related to missing (or invalid) billing keys. Latest version fails more gently in case that happens, also it could have been an issue during install (solved by reinstalling).

If you don't want to use GitHub's. Version `6.0.0` is the latest release.
