### ISSUE TITLE
java.lang.NullPointerException (iabHelper.java:921)

### ISSUE THREAD

**Issue by tuomaslaa** [j3k0/cordova-plugin-purchase#348]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.smartmobilesoftware.util.IabHelper.querySkuDetails(IabHelper.java:921)
       at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:568)
       at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
       at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
       at java.lang.Thread.run(Thread.java:818)
```
            Bundle skuDetails = mService.getSkuDetails(3,  mContext.getPackageName(), itemType, querySkus);

            if (!skuDetails.containsKey(RESPONSE_GET_SKU_DETAILS_LIST)) {
                int response = getResponseCodeFromBundle(skuDetails);
                if (response != BILLING_RESPONSE_RESULT_OK) {
                    logDebug("getSkuDetails() failed: "
                            + getResponseDesc(response));
                    return response;
                } else {
                    logError("getSkuDetails() returned a bundle with neither an error nor a detail list.");
                    return ERR_BAD_RESPONSE;
                }
            }
```

**Comment by tehmaestro** [comment]
Hi. I get this extremely often. Did you manage to solve it?
