### ISSUE TITLE
Make build error

### ISSUE THREAD

**Issue by xdgimf** [j3k0/cordova-plugin-purchase#368]
Any idea why I'm getting this error when running make build?
````
- JSHint
- ESLint
- Mocha

  ․ Ready #ready() should return false at start: 1ms
  ․ Ready #ready() should execute as soon as ready status is set: 0ms
  ․ Errors #callbacks should allow to register error handlers: 0ms
  ․ Errors #trigger() should call registered errors: 0ms
  ․ Errors #trigger() should call all error handlers: 0ms
  ․ Off #off() should exist: 0ms
  ․ Off #off() should allow to remove functions registered with when: 0ms
  ․ Off #off() should allow to remove functions registered with ready: 1ms
  ․ Off #off() should allow to remove functions registered with error: 0ms
  ․ Off #off() should allow to remove functions registered with order: 1ms
  ․ Order #order() should exist and define promises: 0ms
  ․ Queries #uniqueQuery() should remove keywords from the query: 0ms
  ․ Queries #callbacks() should add callbacks: 0ms
  ․ Queries #triggerWhenProduct() should call callbacks: 0ms
  ․ Queries #triggerWhenProduct() should call some callbacks only once: 0ms
  ․ Queries #triggerWhenProduct() should handle special case for subscriptions: 0ms
  ․ Queries #triggerWhenProduct() should execute all callbacks even if one fails with an exception: 0ms
  ․ Queries #triggerWhenProduct() should trigger an update for any event: 1ms
  ․ Queries #triggerWhenProduct() should not trigger an update for error events: 8ms
  ․ Queries #triggerWhenProduct() should not trigger "updated" events twice: 7ms
  ․ Register #register() should exist: 0ms
  ․ Register #register() should allow to register products: 0ms
  ․ Register #register() shouldn't allow to register products containing reserved keywords: 0ms
  ․ Register #register() should fail when registering products without types: 1ms
  ․ When #when() should define chainable promises: 0ms
  ․ When #when() should be called on id: 1ms
  ․ When #when() should be called on aliases: 0ms
  ․ When #when() should allow direct callback registrations: 1ms
  ․ When #when() should allow non product related registrations: 0ms
  ․ When #once() should be called once on id: 1ms
  ․ When #once() should be called once on aliases: 0ms
  ․ Finish #finish should trigger the finish event: 2ms
  ․ Verify #verify should return a Promise: 0ms
  ․ Verify #verify should call the validator when state is APPROVED: 4ms
  ․ Verify #verify should retry 5 times when validator fails: 55ms
  ․ Utils #ajax should allow simple requests: 3ms
  ․ Utils #ajax should handle errors: 2ms
  ․ Utils #ajax should handle failing success callbacks: 3ms
  ․ iOS #init should initialize storekit at first refresh(): 32ms
  ․ Android #init should: 0ms

  40 passing (146ms)

done

- Preprocess
Parse error at -:2027,27
Unexpected token: eof (undefined)
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2033:9)
    at unexpected (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2039:9)
    at block_ (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2351:28)
    at eval (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2325:25)
    at function_ (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2330:15)
    at expr_atom (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2538:24)
    at maybe_unary (eval at <anonymous> (/Users/Miguel/Repo/wc-cordova-plugin-purchase/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2708:19)
make: *** [build] Error 1
````

**Comment by seibelj** [comment]
same issue for me

**Comment by seibelj** [comment]
I modified the build section of the makefile to be:

```
build: sync-android test-js
	@echo "- Preprocess"
	@node_modules/.bin/preprocess src/js/store-ios.js src/js > foo.txt
	@cat foo.txt | node_modules/.bin/uglifyjs -b > www/store-ios.js
	@rm foo.txt
	@node_modules/.bin/preprocess src/js/store-android.js src/js > moo.txt
	@cat moo.txt | node_modules/.bin/uglifyjs -b > www/store-android.js
	@rm moo.txt
	@node_modules/.bin/preprocess src/js/store-windows.js src/js > woo.txt
	@cat woo.txt | node_modules/.bin/uglifyjs -b > www/store-windows.js
	@rm woo.txt
	@echo "- Done"
	@echo ""```

This works, no idea why piping is failing directly from the command. By putting it in a file first and then cat-ing it to uglify, it builds without error

**Comment by j3k0** [comment]
Weird, but probably worth a pull request to save others some pain. Maybe name `foo.txt` as `.build.tmp` or something... And add this file to `.gitignore`...
