### ISSUE TITLE
Many crashes report from Play Store console: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tominou** [j3k0/cordova-plugin-purchase#589]
Here is the full report:

> java.lang.NullPointerException: 
  at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:831)
  at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:576)
  at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
  at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
  at java.lang.Thread.run(Thread.java:762)

Thank you!

**Comment by Dexus** [comment]
Can you please report us more details? Like sdk version, Cordova version, etc. all that will help us to look deeper into it. Because its difficult to create a similar env and setup like you have. 

Von meinem iPhone gesendet

**Comment by alexplummer** [comment]
I am also getting this, how come you marked it as closed? Is there a solution?

**Comment by Dexus** [comment]
Reopen a new Issue with more datails i dont can reproduce this in out in the blue...
