### ISSUE TITLE
ANDROID Crash NullPointerException com.smartmobilesoftware.util.IabHelper.queryPurchases

### ISSUE THREAD

**Issue by jasonandress** [j3k0/cordova-plugin-purchase#615]
I'm getting several crash reports from the Play store on my app. I don't  have many test phones and it hasn't happened to me so I can't say what the users were doing. I don't have very complicated code. I simply query the store each time they start the app or login. And call the order method when they buy.

Cordova: 6.5.0
Cordova Android: 6.2.1
Android OS: 6.0 and 7.0
Plugin Version: 6.0.0

java.lang.NullPointerException: 
  at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:837)
  at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:562)
  at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
  at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
  at java.lang.Thread.run(Thread.java:833)

### Expected behavior
Won't have this error

### Observed behavior
The error above.

### Steps to reproduce
Not sure

**Comment by gpaslari** [comment]
@jasonandress, did you manage to fix your issue?
