### ISSUE TITLE
[Android] Cannot install on cordova-android > 6.4.0

### ISSUE THREAD

**Issue by gabn88** [j3k0/cordova-plugin-purchase#679]
### system info
cordova-android 7.1.0
plugin commit 95ce2b0638324d975cbbbc1844f12982f0f9caf5 

### Expected behavior
Cannot add plugin.

### Observed behavior

Failed to install 'cc.fovea.cordova.purchase': Error: ENOENT: no such file or directory, open 'C:\Apps\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (C:\Apps\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (C:\Apps\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (C:\Apps\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (C:\Apps\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)

(node:19964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\Apps\platforms\android\AndroidManifest.xml'

### Steps to reproduce

Try to install plugin on cordova-android > 6.4.0

**Comment by aesculus** [comment]
Try version 7.1.2

It has the new Android file location and the old one

**Comment by epetre** [comment]
@aesculus where did you see version 7.1.2 being available?

**Comment by aesculus** [comment]
I meant the plugin version. It's now at 7.1.3

**Comment by epetre** [comment]
oh gotcha, thx!

**Comment by gabn88** [comment]
@aesculus Thanks, it works. Super nice.
