### ISSUE TITLE
[ANDROID] java.lang.SecurityException: Requires READ_PHONE_STATE on Android 5.1

### ISSUE THREAD

**Issue by mifkys** [j3k0/cordova-plugin-purchase#732]
### system info

```
Cordova 6.5
Device: Android 5.1
Plugin Version: 7.2
```

I received from user phones several crash logs with this error:
```
java.lang.SecurityException: Requires READ_PHONE_STATE: Neither user 10645 nor current process has android.permission.READ_PHONE_STATE.
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:756)
	at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2009)
	at android.telephony.TelephonyManager.getNetworkOperatorName(TelephonyManager.java:1122)
	at android.telephony.TelephonyManager.getNetworkOperatorName(TelephonyManager.java:1094)
	at com.ironsource.environment.DeviceStatus.getMobileCarrier(DeviceStatus.java:143)
	at com.ironsource.sdk.utils.DeviceProperties.<init>(DeviceProperties.java:25)
	at com.ironsource.sdk.utils.DeviceProperties.getInstance(DeviceProperties.java:30)
	at com.ironsource.sdk.controller.IronSourceWebView.getRequestParameters(IronSourceWebView.java:3040)
	at com.ironsource.sdk.controller.IronSourceWebView.load(IronSourceWebView.java:2523)
	at com.ironsource.sdk.controller.IronSourceWebView.onFileDownloadSuccess(IronSourceWebView.java:3600)
	at com.ironsource.sdk.precache.DownloadManager$DownloadHandler.handleMessage(DownloadManager.java:117)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5643)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
Google talks that this error relating to in App Billing on Android Marshmallow and some other versions of Android:
https://stackoverflow.com/questions/38131475/inapp-billing-java-lang-securityexception-requires-read-phone-state
https://productforums.google.com/forum/#!topic/play/4LigT3eyQgk

So I think this error also related to this plugin. Need additional information to resolve this issue?

**Comment by j3k0** [comment]
@mifkys Can you try #739 ? I don't have a phone with this issue, so it's just a "blind fix" based on stackoverflow's  proposed solution.

In case you don't know how to install the plugin from a PR:

cordova plugin add 'https://github.com/j3k0/cordova-plugin-purchase.git#fix/android-readphonestate'
