### ISSUE TITLE
Error when Reinstall ( IInAppBillingService.aidl already exists! ) 

### ISSUE THREAD

**Issue by arijitnaskar** [j3k0/cordova-plugin-purchase#742]
I tried to upgrade the version to 7.2.1 from 7.2.0 to get rid from issue #729

I uninstalled the plugin with billing key.
`cordova plugin remove cc.fovea.cordova.purchase --variable BILLING_KEY="<my billing key>"`

```
Uninstalling cc.fovea.cordova.purchase from android
Android Studio project detected
config file res/values/billing_key_param.xml requested for changes not found at /home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/res/values/billing_key_param.xml, ignoring
config file app/src/main/res/values/billing_key_param.xml requested for changes not found at /home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/app/src/main/res/values/billing_key_param.xml, ignoring
Removing "cc.fovea.cordova.purchase"
Removing plugin cc.fovea.cordova.purchase from config.xml file...
Removing cc.fovea.cordova.purchase from package.json
```

This successfully un installed the plugin.

Then when I tried to  reinstall,

`cordova plugin add cc.fovea.cordova.purchase  --variable BILLING_KEY="<my billing key>"`

I am getting the below error:
`platform/android/src/com/android/vending/billing/IInAppBillingService.aidl already exixts!`

Also I tried to install after manually deleting the file IInAppBillingService.aidl.
Still no luck.

**Full stack trace:**

```
Installing "cc.fovea.cordova.purchase" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cc.fovea.cordova.purchase': CordovaError: Uh oh!
"/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/src/com/android/vending/billing/IInAppBillingService.aidl" already exists!
    at copyNewFile (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/lib/pluginHandlers.js:261:45)
    at install (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/lib/pluginHandlers.js:51:17)
    at ActionStack.process (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/cordova/node_modules/q/q.js:556:49
Uh oh!
"/home/arijit/Development/AndroidApp/Croaking Jump/platforms/android/src/com/android/vending/billing/IInAppBillingService.aidl" already exists!

```

Please suggest how can I upgrade to 7.0.1

**Comment by jellomaster** [comment]
Have same issue here.  I tried manually deleting the file it complains about, however the installation still crashes with the same error and IInAppBillingService.aidl appears again in the directory.  Also tried removing the plugin and running "cordova clean android"... that command removes some extra files however installation still crashes with the same error.

**Comment by arijitnaskar** [comment]
@j3k0 thanks for you reply. The issue is still there. Please look when you get time.

**Comment by j3k0** [comment]
Looks like a bug with cordova, which should remove `IInAppBillingService.aidl` as plugin removal but doesn't. d80f3b3 should do the trick.

**Comment by teamgeist-app** [comment]
This issue resurfaced for me. Maybe since the androidBeforeInstall script is not included anymore in the latest version?
