### ISSUE TITLE
cordova android build error - The "path" argument must be of type string

### ISSUE THREAD

**Issue by brsmurf1** [j3k0/cordova-plugin-purchase#756]
# !!! PLEASE USE IN SUBJECT [IOS] OR [ANDROID] AS PREFIX FOR YOUR ISSUE !!!

### system info

OSX high Sierra 10.13.6
Cordova 8.1.2
npm 6.4.1
cordova-android 7.1.2

When I add android platform in  cordova, I got this error. 
I found somtimes it occur from 'path.resolve()'. 
but what shall i do? 

//---
Failed to install 'cc.fovea.cordova.purchase': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at copyNewFile (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/lib/pluginHandlers.js:258:28)
    at install (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/node_modules/q/q.js:834:54)
    at /Users/urbanist/Desktop/web/cordova/trcng_new/platforms/android/cordova/node_modules/q/q.js:863:30

**Comment by j3k0** [comment]
I just tried with on my mac:

 * plugin version 7.2.4
 * cordova 8.1.2 (cordova-lib@8.1.1)
 * node v10.12.0
 * macOS 10.14.1
 * npm 6.4.1

Sounds like an issue with cordova.

The bug is in the function that install source files to the appropriate location `platforms/android/cordova/lib/pluginHandlers.js`. You might be able to debug it, or report to the cordova-android folks.

I just checked: https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/pluginHandlers.js

It seems a recent PR was made to solve the issue:
https://github.com/apache/cordova-android/pull/490

Cordova-android 7.1.2 has been recently released:
https://cordova.apache.org/announcements/2018/11/07/cordova-android-7.1.2.html

Worth giving it a try!

    cordova platform remove android
    cordova platform add android@7.1.2

**Comment by brsmurf1** [comment]
Thanks, You are right. 
 I'll try ..
cordova platform add android@7.1.1  - success, 
cordova platform add android$7.1.2 is - fail

**Comment by surya-alive** [comment]
Hi,, I've same issue here.
I tried to upgrade 7.1.2 and the result still not working

**Comment by j3k0** [comment]
Hi @surya-alive, it seems like you have to use `7.1.1`. The cordova team is on it: https://github.com/apache/cordova-android/issues/540

**Comment by surya-alive** [comment]
@j3k0 Thanks for your comment.. it's work on `7.1.1`

**Comment by brodybits** [comment]
I recommend using cordova-android@nightly until we publish a patch release.

Patch release is proposed in:
https://github.com/apache/cordova-android/pull/555

Keep in mind that nightly or master has sone possibly breaking changes for
the next major release.

**Comment by nagthgr8** [comment]
in my case the issue resolved when I remove & then add platform android looks like for every cordova update this step is mandatory

**Comment by brodybits** [comment]
> [...] when I remove & then add platform android looks like for every cordova update this step is mandatory

I had a similar experience, Cordova does not seem to do npm-style package updates. Not sure if someone may have fixed it in master or not.

**Comment by PatAbah** [comment]
2020. same issue here

**Comment by j3k0** [comment]
> 2020. same issue here

That would mean you're using an old version of cordova-android. The issue was definitely fixed 2 years ago. What version of cordova-android and the plugin are you using? You can paste the output of `cordova info` (run in your project) for details.
