### ISSUE TITLE
[ANDROID] cordova-plugin-purchase fails to install in latest cordova environment

### ISSUE THREAD

**Issue by nagthgr8** [j3k0/cordova-plugin-purchase#758]
### system info

Ionic:

   ionic (Ionic CLI)  : 4.3.1 (C:\Users\Hamsini\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : no whitelisted plugins (13 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Hamsini\AppData\Local\Android\sdk)
   NodeJS            : v9.3.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.10.0
   OS                : Windows 10

### Expected behavior
Plugin should install
### Observed behavior
Fails to install with below error
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cc.fovea.cordova.purchase': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string
at assertPath (path.js:28:11)
at Object.resolve (path.js:221:7)
at copyNewFile (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:258:28)
at install (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:43:17)
at ActionStack.process (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
at PluginManager.doOperation (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
at PluginManager.addPlugin (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
at C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\Api.js:247:74
at _fulfilled (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\q\q.js:834:54)
at self.promiseDispatch.done (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\q\q.js:863:30)
Uh oh!
The "path" argument must be of type string
### Steps to reproduce
upgrade ionic & cordova to the latest(ref. system info above)

remove & add android platform

cordova platform rm android
cordova platform add android

remove and add in-app-purchase-2 plugin
ionic cordova plugin rm cc.fovea.cordova.purchase
ionic cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="MYBILLINGKEY"

**Comment by Dexus** [comment]
Please see #756

It’s not a bug in our plugin!

**Comment by nagthgr8** [comment]
This issue is resolved after i remove & then add >ionic cordova platform add android the error message is quite misleading though
thank you

**Comment by nagthgr8** [comment]
when i add corova platform as below the same error appears again, not sure if this is cordova problem or the plugin

```
C:\MobileApps\HYBRID\vedichoroo>cordova platform add android@7.1.2
Using cordova-fetch for cordova-android@7.1.2
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.mypubz.eportal
        Name: vedichoroo
        Activity: MainActivity
        Android target: android-27
Android project created with cordova-android@7.1.2
Android Studio project detected
Android Studio project detected
Installing "cc.fovea.cordova.purchase" for android
Error during processing of action! Attempting to revert...
Failed to install 'cc.fovea.cordova.purchase': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at copyNewFile (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:258:28)
    at install (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:43:17)
    at ActionStack.process (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
```
