### ISSUE TITLE
[ANDROID]: Cannot assign to read only property 'state' of object '[object Object]'

### ISSUE THREAD

**Issue by paulstelzer** [j3k0/cordova-plugin-purchase#785]
### Expected behavior

I don't know if this is interesting for you, so you can also close this issue. But I want to let you know the following:

I have enabled a developmentmode by ngxs ( https://github.com/ngxs/store/issues/716#issuecomment-447989673 ). That freezes any object in a state, so it cannot be mutated.

It seems that your plugin (only tested on Android) trys to mutate his state.

As I said in the beginning that is no bug or something like this. It's just part of a paradigm not to mutate a state. So it's just nice to know ;) In production mode this is deactivated, so there everything is of course working :) 

### Observed behavior

The cordova plugin version has to be `cc.fovea.cordova.purchase@7.2.5`, but sometimes he still use `cc.fovea.cordova.purchase@7.3.0-beta.0`

```
http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js: Line 1595 : [store.js] WARNING: A callback in 'ready.callback' failed with an exception.
12-18 18:12:23.671 32747-32747/my.app.id I/chromium: [INFO:CONSOLE(1595)] "[store.js] WARNING: A callback in 'ready.callback' failed with an exception.", source: http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js (1595)
12-18 18:12:23.671 32747-32747/my.app.id D/SystemWebChromeClient: http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js: Line 1595 : [store.js] WARNING:            Cannot assign to read only property 'state' of object '[object Object]'
12-18 18:12:23.671 32747-32747/my.app.id I/chromium: [INFO:CONSOLE(1595)] "[store.js] WARNING:            Cannot assign to read only property 'state' of object '[object Object]'", source: http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js (1595)
12-18 18:12:23.671 32747-32747/my.app.id D/SystemWebChromeClient: http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js: Line 1595 : [store.js] WARNING:            TypeError: Cannot assign to read only property 'state' of object '[object Object]'
      at store.Product.set (http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js:1682:19)
      at Object.<anonymous> (http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js:1197:11)
      at Object.callExternal (http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js:2053:36)
      at http://localhost:8219/plugins/cc.fovea.cordova.purchase/www/store-android.js:1279:29
      at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8219/polyfills.js:5417:31)
      at Object.onInvokeTask (http://localhost:8219/vendor.js:57603:33)
      at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8219/polyfills.js:5416:36)
      at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8219/polyfills.js:5184:47)
      at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:8219/polyfills.js:5492:34)
      at ZoneTask.invoke (http://localhost:8219/polyfills.js:5481:48)
```

**Comment by j3k0** [comment]
Thanks @paulstelzer 

Indeed the plugin doesn't implement immutable states, quite the opposite. "Products" objects are mutated to always represent the most up to date information we have about them. There are pros and cons to both approach, but I guess at this points I won't consider changing that...

I suppose you'll have to deep-clone the product objects when you retrieve them to make sure your state is immutable.

I'm closing since I don't think it's something we'll address anytime soon.
