### ISSUE TITLE
[ANDROID] The app will stop after the native payment window pops up

### ISSUE THREAD

**Issue by tmhrbr** [j3k0/cordova-plugin-purchase#924]
Hey guys, I am working with a Japanese android tv device where I am struggling with this issue. The app is working on every other device that we have tried it on, for example Sony KD-43XF7596.

### system info
OS: Android 8.0.0
Cordova 7.1.0, Cordova-android 6.4.0
Device: https://www.androidtv-guide.com/pay-tv-provider/kddi-cableplus-stb-2

### Expected behavior
When I start the payment process, the native payment window will pop up and when I am finished, I am redirected back to the app

### Observed behavior
When the payment process is initiated, the native android payment window pops up it will pause and after a few hundred milliseconds stops the app. When I close the window, either by going back or finish the payment process, I will end up in android home page.

Thanks in advance,
Tom

**Comment by Dexus** [comment]
Hi,
this can be hard to debug. Can you provide some logs?

Regards, Josef

Von meinem iPhone gesendet

**Comment by tmhrbr** [comment]
Sure, here is the log when I initiate the payment and the native window pops up:
`
2019-08-30 09:48:14.116 3301-4263/? I/ActivityManager: START u0 {act=com.google.android.finsky.tv.IABV3_PURCHASE dat=iabData:subs:com.myapp.test:jp.mp.ft.01.test cmp=com.android.vending/com.google.android.finsky.billing.lightpurchase.pano.TvIabV3Activity (has extras)} from uid 10029
2019-08-30 09:48:14.120 9020-9020/com.myapp.test D/CordovaActivity: Paused the activity.
2019-08-30 09:48:14.155 9020-9020/com.myapp.test W/ViewRootImpl[MainActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=353, metaState=0, flags=0x28, repeatCount=0, eventTime=1344908, downTime=1344856, deviceId=9, source=0x701 }
2019-08-30 09:48:14.260 5178-5178/? I/Finsky: [2] ror.a(63): Skipping DFE self-update. Local Version [81613568] >= Server Version [-1]
2019-08-30 09:48:14.271 5178-10104/? E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
2019-08-30 09:48:14.299 5178-5178/? W/ViewRootImpl[TvIabV3Activity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=353, metaState=0, flags=0x28, repeatCount=0, eventTime=1344912, downTime=1344856, deviceId=9, source=0x701 }
2019-08-30 09:48:14.299 5178-5178/? I/chatty: uid=10029(u0_a29) com.android.vending identical 7 lines
2019-08-30 09:48:14.299 5178-5178/? W/ViewRootImpl[TvIabV3Activity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=353, metaState=0, flags=0x28, repeatCount=0, eventTime=1344912, downTime=1344856, deviceId=9, source=0x701 }
2019-08-30 09:48:14.317 3301-4316/? W/ActivityManager: Unable to start service Intent { act=android.support.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
2019-08-30 09:48:14.321 5178-5231/? E/ActivityThread: Failed to find provider info for telephony
2019-08-30 09:48:14.336 5178-5178/? I/Finsky: [2] rja.a(3): Canceling job 16-16161616
2019-08-30 09:48:14.369 3301-3441/? I/ActivityManager: Displayed com.android.vending/com.google.android.finsky.billing.lightpurchase.pano.TvIabV3Activity: +242ms
2019-08-30 09:48:14.374 5178-5178/? I/Finsky: [2] rio.b(5): Jobs in database: 1-1337 24-77777777 26-1414141414 
2019-08-30 09:48:14.374 5178-5178/? I/Finsky: [2] rfp.a(59): ConstraintMapping: 24-77777777,  -> L: 0ms, D: 81551138ms, C: false, I: true, N: 0
2019-08-30 09:48:14.375 5178-5178/? I/Finsky: [2] rfp.a(59): ConstraintMapping: 1-1337,  -> L: 35622301ms, D: 78822301ms, C: false, I: false, N: 1
2019-08-30 09:48:14.375 5178-5178/? I/Finsky: [2] rfp.a(59): ConstraintMapping: 26-1414141414,  -> L: 41945507ms, D: 42845507ms, C: false, I: false, N: 0
2019-08-30 09:48:14.377 5178-5178/? I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(45): Cancelling existing jobscheduler jobs: 9002 9001 9005 
2019-08-30 09:48:14.378 5178-5178/? I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(1): Scheduling job Id: 9000, L: 0, D: 81551138, C: false, I: true, N: 0
2019-08-30 09:48:14.379 5178-5178/? I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(1): Scheduling job Id: 9003, L: 35622301, D: 78822301, C: false, I: false, N: 1
2019-08-30 09:48:14.382 5178-5178/? I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(1): Scheduling job Id: 9004, L: 41945507, D: 42845507, C: false, I: false, N: 0
2019-08-30 09:48:14.418 5178-5178/? I/Finsky: [2] lfn.a(262): Installer: found apps to install. apps=[]
2019-08-30 09:48:14.446 3111-3111/? D/SurfaceFlinger: Backpressure trigger, skipping transaction & refresh!
2019-08-30 09:48:14.645 3111-3111/? D/SurfaceFlinger: Backpressure trigger, skipping transaction & refresh!
2019-08-30 09:48:14.785 9020-9020/com.myapp.test D/CordovaActivity: Stopped the activity.
2019-08-30 09:48:14.785 9020-9020/com.myapp.test D/CordovaActivity: CordovaActivity.onDestroy()
2019-08-30 09:48:14.786 9020-9020/com.myapp.test D/CordovaPurchase: Destroying helper.
2019-08-30 09:48:14.786 9020-9020/com.myapp.test D/IabHelper: Disposing.
2019-08-30 09:48:14.786 9020-9020/com.myapp.test D/IabHelper: Unbinding from service.
2019-08-30 09:48:14.789 9020-9020/com.myapp.test D/CordovaWebViewImpl: >>> loadUrl(about:blank)
2019-08-30 09:48:14.792 9020-9020/com.myapp.test W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
2019-08-30 09:48:14.852 9020-9020/com.myapp.test W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.a(PG:378)
        at org.chromium.android_webview.AwContents.r(PG:659)
        at zF.loadingStateChanged(PG:135)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-08-30 09:48:14.861 3301-4294/? I/ActivityManager: Killing 10412:com.google.android.webview:sandboxed_process2/u0a124i20 (adj 0): isolated not needed
2019-08-30 09:48:14.861 3301-3406/? W/zygote: failed to open /acct/uid_99020/pid_10412/cgroup.procs: No such file or directory
2019-08-30 09:48:15.365 3301-4294/? W/AppOps: Bad call: specified package com.google.android.gms under uid 10029 but it is really 10026
    java.lang.RuntimeException: here
        at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1319)
        at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1038)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
        at android.os.Binder.execTransact(Binder.java:674)
`

and here when I close the window
`2019-08-30 09:51:55.855 4319-11322/? E/ActivityThread: Failed to find provider info for tvlauncher.mic
2019-08-30 09:51:55.855 4319-4319/? I/PrtnrWidgetInfoLdr: Failed to register content observer for URI: content://tvlauncher.widget/widget.
    Reason: Failed to find provider tvlauncher.widget for user 0; expected to find a valid ContentProvider for this authority
2019-08-30 09:51:55.860 4319-11323/? E/ActivityThread: Failed to find provider info for tvlauncher.widget
2019-08-30 09:51:55.863 4319-4319/? I/AppLifecycleTracker: onActivityResumed: 
2019-08-30 09:51:55.866 4249-4249/? D/NotifInteractonRcvr: Show unseen default level notification toasts
2019-08-30 09:51:56.391 5178-5178/? I/Finsky: [2] nzq.onTrimMemory(1): Memory trim requested to level 20
2019-08-30 09:51:56.391 5178-5178/? I/Finsky: [2] nzq.onTrimMemory(2): Flushing in-memory image cache
2019-08-30 09:51:58.258 3045-3078/? I/nxserver: mmu-cand@8[0]:5178::score:15::cnt:7
2019-08-30 09:51:58.861 4249-7041/? D/TVNotifService: getConnectedInstanceBlocking - block
2019-08-30 09:51:58.861 4249-7041/? D/TVNotifService: getConnectedInstanceBlockingWithTimeout - done
2019-08-30 09:51:58.871 4319-4319/? E/Clearcut-EventLogger: Unexpected log parameter tray_notification_count
2019-08-30 09:51:59.440 3301-3648/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2019-08-30 09:52:00.956 5280-5447/? I/chromium: [5280:5447:INFO:mdns_app_filter.cc(2437)] MdnsAppFilter: responses sent in 30 seconds: 25
`

Thanks
