### ISSUE TITLE
[iOS] Cannot install: missing variable BILLING_KEY

### ISSUE THREAD

**Issue by nielsjakob** [j3k0/cordova-plugin-purchase#929]
```
OSX Mojave 10.14.6 (18G95)
Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-plugin-purchase 8.1.1 "Purchase"
```

### Expected behavior
I try to install the plugin via Terminal in my project folder with:
`cordova plugin add cordova-plugin-purchase [--variable BILLING_KEY="MIIB...QAB"]`

Since I only care about iOS at the moment, I have also tried the following, which unfortunately yields exactly the same error message:
`cordova plugin add cordova-plugin-purchase`

### Observed behavior
Terminal returns the following error message:
```
Installing "cordova-plugin-purchase" for android
Failed to install 'cordova-plugin-purchase': Error: Variable(s) missing: BILLING_KEY
    at Object.mergeVariables (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/variable-merge.js:58:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:307:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Variable(s) missing: BILLING_KEY
```

Even though it says that the installing failed, the plugin is listed under `cordova plugin list` as
`cordova-plugin-purchase 8.1.1 "Purchase"`

However, f I do a `console.log(window.store)` in my app, it returns `undefined`. And if I try to register a product, nothing happens.

### On a side note
If I then try to uninstall the plugin via `cordova plugin remove cordova-plugin-purchase`, it does not work and Terminal only returns `Variable(s) missing: BILLING_KEY`

**Comment by nielsjakob** [comment]
I installed using this PR and it worked:

https://github.com/j3k0/cordova-plugin-purchase/pull/911
